### ISSUE TITLE
Compatibility with New Version of Confluence

### ISSUE THREAD

**Issue by jfry37** [coldrye-confluence/top-labels-plugin#1]
Will you be updating this app to be compatible with the newest version of Confluence? How long do you plan on supporting this plug-in?

**Comment by silkentrance** [comment]
Compatibility has already been update to the latest version 7.6.2.

Confluence Server 6.10.0 - 7.6.2

**Comment by silkentrance** [comment]
@jfry37 or is there a problem with the latest version with top labels plugin no longer working as expected?

**Comment by silkentrance** [comment]
just upgraded to confluence 7.6.2 and all is working fine.
